### ISSUE TITLE
Trying to run example code

### ISSUE THREAD

**Issue by DePasqualeOrg** [lucasnewman/e2-tts-mlx#1]
This looks really promising. I'm trying to run the example from the readme, but after running `pip install mlx-e2-tts` and then the code block under "Usage", I get this error: `No module named 'g2p_en'`

Also, could you provide an example of generating audio with a pre-trained model?

**Comment by lucasnewman** [comment]
@DePasqualeOrg Try the follow up project which has a pretrained model available: https://github.com/lucasnewman/f5-tts-mlx

If you want to install g2p for phonemization, you can do `pip install g2p-en`
